// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpTNF7aqlpky7xaVoeq2C0Zfx65ezAQLw',
    appId: '1:291057453009:web:0c22b56479b76618c042f0',
    messagingSenderId: '291057453009',
    projectId: 'grace-coffee-app',
    authDomain: 'grace-coffee-app.firebaseapp.com',
    storageBucket: 'grace-coffee-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoA-JjdN4UIR_agSZXQpuezUpYRX7_Uxg',
    appId: '1:291057453009:android:29531b4a631ccbb8c042f0',
    messagingSenderId: '291057453009',
    projectId: 'grace-coffee-app',
    storageBucket: 'grace-coffee-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEr0jX_Lwc_XAgzm_JGmiq45Due1Y9GkY',
    appId: '1:291057453009:ios:91e5291c16241782c042f0',
    messagingSenderId: '291057453009',
    projectId: 'grace-coffee-app',
    storageBucket: 'grace-coffee-app.firebasestorage.app',
    iosClientId:
        '291057453009-uotis1lhcgpalm9i48ihqbhg273571cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gracecoffeehouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEr0jX_Lwc_XAgzm_JGmiq45Due1Y9GkY',
    appId: '1:291057453009:ios:91e5291c16241782c042f0',
    messagingSenderId: '291057453009',
    projectId: 'grace-coffee-app',
    storageBucket: 'grace-coffee-app.firebasestorage.app',
    iosClientId:
        '291057453009-uotis1lhcgpalm9i48ihqbhg273571cs.apps.googleusercontent.com',
    iosBundleId: 'com.example.gracecoffeehouse',
  );
}
